### ISSUE TITLE
Feature Request: Add Paul's map style tag 

### ISSUE THREAD

**Issue by Vazyriqx** [beatmaps-io/beatsaver-main#127]
Pauls should cover pauls and poodles. No need for a seperate tag for both.

This is a distinquished map style that it doesn't apropriately fit under the other tags on beatsaver (I am including challege before someone mentions that) 

Arguements for it:

- There is a very large map base for paul/paul maps. 

- Large player base. Based off hitbloq statistcs every week there averages about 150 people playing in the "Dunny HaHa Pauls" pool and 100 in the "Pauls" pool. Both pools since creation have remained in hitbloqs top 10 most active played pools. Usually with at least one in the top 5 most active. (It is important to note only people who have signed up to hitbloq are counted so this only represents a portion of people who play pauls the actual numbers may be higher) 

Links:
Hitbloq Ascoiated links:

-  [Pools sorted by activity](https://hitbloq.com/map_pools)
-  [Funny HaHa Pauls map list](https://hitbloq.com/map_pool/funny_haha_pauls)
-  [Pauls map list](https://hitbloq.com/map_pool/paul)
 

[Beatsaver Search for poodles](https://beatsaver.com/?q=poodles)
[Beatsaver Search for paul](https://beatsaver.com/?q=paul) (Note this search is not brilliant as artsits and authers named paul interfere with the search)

**Comment by Top-Cat** [comment]
To preface this response we really don't want to add tags, the more tags there are the harder it is to only have two that are relevant and the harder it is to actually find things.

While they are in weekly activity the total number of people in those pools is FAR lower than many pools with much lower weekly activity which leads me to believe a small minority is playing these maps over and over rather than many people wanting to play them.

Your claim that there is a large map base has no evidence other than two searches which I'm not going to go through to determine if each map fits the "style".

I'd recommend in the short term to compile a playlist of paul maps (as existed for maps using arcs and chains when the feature was added) that people can use to find maps they want to play. Playlist discoverability is already on the roadmap.

**Comment by Vazyriqx** [comment]
Regarding 
> Your claim that there is a large map base has no evidence other than two searches which I'm not going to go through to determine if each map fits the "style".

I meant to use the hitbloq map pools as it is already a large list of maps. These were linked at the bottom of the post
