### ISSUE TITLE
[Request] API addition - # of pages / # of maps

### ISSUE THREAD

**Issue by vaser888** [beatmaps-io/beatsaver-main#18]
I'm not sure if this is the right place to request things regarding the BeatSaver API but there is one think that I miss in the new API. When receiving the data in the past, it would display the total number of maps and or the total number of pages that would fit the request in the json. It's now gone and impossible to make page based features/sites without having to test for an empty response.

If it's not too difficult to add, it would be nice to have that data back in the json. 
If it was removed for a reason then that's fine and I'll live without it.

**Comment by Top-Cat** [comment]
Getting the total number of records doubles the query count and potentially response time of the endpoints.
Further, actually paging to the end of a result set is not efficient (which is why the /latest endpoint doesn't use pages at all)

Of course this doesn't actually stop you. You can still make sites that have next/previous buttons instead of infinite scroll without these values, the only thing you're missing is the "last" page button.
