### ISSUE TITLE
How to add songs

### ISSUE THREAD

**Issue by Firenickname01** [beatmaps-io/beatsaver-main#420]
I have a question if this is the right one most of the tutorials are useless so how do I add songs to beat saber so I can play them

**Comment by TimothyGillespie** [comment]
Hi, this would be the wrong place to get help for this.

Many tutorials have become outdated, you may find this up2date article useful (especially the later part): https://bsaber.com/getting-started/custom-songs

Otherwise, BSMG has a Discord where you could get more help. Here is their website (Discord server is as also linked there): https://bsmg.wiki/
