### ISSUE TITLE
[Request] Way to get map deletions in the past from the API

### ISSUE THREAD

**Issue by patagonaa** [beatmaps-io/beatsaver-main#449]
I'm scraping the Beatsaver API to create my own copy to run queries against (so I have more control and I don't create unnecessary load on the API) for https://github.com/patagonaa/BeatSaverMatcher.

Previously, after finding the beatmaps in my database, I always fetched them from the beatsaver API so I could get the current score/rating and check if they were deleted.

Now, I've switched to fetching map changes via `/maps/latest?sort=UPDATED&after=[...]` and updating the scores using `/vote?since=[...]` so I don't have to fetch the maps from the API after searching. Only thing missing now is the possibility to get which maps have been deleted.

There _is_ the websocket API which includes events for deleted maps, but that doesn't work for the past or while my service is down.

Is there a way to get which maps have been deleted since a certain date? My preferred way would be if there was an option in `/maps/latest` to include deleted maps.

Also, I'm not sure if it's a good idea that the `/vote` API returns like 40.000 entries at once if the `since` date is set very early (like I did to populate my database), an updated-date for each entry and a limited page size might make sense there as well.

**Comment by Top-Cat** [comment]
I've added a PR to add an endpoint `/api/maps/deleted` that works exactly like /maps/latest but only supplies the id/deleted time of maps. See https://github.com/beatmaps-io/beatsaver-main/pull/450

You can't page the `/vote` endpoint as it's likely the data will change between requests and the paging will just break.

Imagine the page size is 5. Requesting since 10:00, you get A (10:01), B (10:02), C (10:03), D (10:04), E (10:05).
Now before you ask for a new page A gets a new vote (10:10).
Requesting since 10:00, page 2 you now get G (10:06), H (10:07), I (10:08), J (10:09), A (10:10).
You've now missed F completely.

The response is slow but I'm not currently worried about the impact of calling /vote like this.

**Comment by patagonaa** [comment]
> I've added a PR to add an endpoint `/api/maps/deleted` that works exactly like /maps/latest but only supplies the id/deleted time of maps. See #450

Looks good, that would be awesome, thanks for the quick response.


> You can't page the `/vote` endpoint as it's likely the data will change between requests and the paging will just break.

I was more thinking about a count limitation in combination with the introduction of a date/time field, so:
- Request votes since 10:00 -> Server returns the first 100 votes and their update date (10:01, 10:02, [...], 10:30)
- Request votes since 10:30 (time of latest vote from reponse) -> Server returns the next 100 votes (10:31, 10:32, [...])
- [repeat until the server returns less than 100 votes, then we're up to date]

Which is basically what I'm currently doing to get the map updates using `/api/maps/latest`, I start at the latest update date in my DB and fetch the next 100 maps after the update-date until the server returns none.

> The response is slow but I'm not currently worried about the impact of calling /vote like this.

Yea, as long as the server load isn't an issue, this isn't really necessary

**Comment by Top-Cat** [comment]
May look into adding a limit for /vote in the future but I'll close this issue as it was really around deletions
